### ISSUE TITLE
2optout Interoperability

### ISSUE THREAD

**Issue by tbranyon** [CourseReps/ECEN489-Spring2016#1]
@CourseReps/team-ecen489-spring2016 

For anyone who is doing the optout challenge, we need to establish some sort of standard for the way our data is represented and transmitted so our servers/clients will work together.

We could have one common class that we share that implements `Serializable` and contains fields for all the required information so that we all have the same object and we can simply send and receive that object. Any thoughts from anyone?

UPDATE: I have this class now that successfully can be sent a received over a socket. If there are no objections, we can use this: [ComputerData.java](https://github.com/CourseReps/ECEN489-Spring2016/blob/master/Students/tbranyon/2optout/ComputerData.java)  

I could also include accessor ("get") methods for each field if that is desired.

**Comment by Fanchao92** [comment]
Just a question here, when we say the server and the client to be 'interactive', do we need to make this interaction half-duplex or full-duplex?

**Comment by tbranyon** [comment]
I don't think full-duplex is needed based on the assignment description. The server doesn't need to/shouldn't send until it receives the request from the client, and the client won't need to receive until after it has sent the request. 

Also I just realized that the date and time are supposed to be included in the information as well...

**Comment by Fanchao92** [comment]
OK, I see. I took it wrong. I thought after the client got the info. from the server, they still needed to stay online and communicate, until any of them cut off the link.

**Comment by tbranyon** [comment]
We should also standardize the way the client asks for the data. Maybe on connection the client just sends the string "get_data"?
