### ISSUE TITLE
Pong

### ISSUE THREAD

**Issue by samshore** [CourseReps/ECEN489-Spring2016#10]
Hey if someone with a Windows computer could download my files from this dropbox link we could do the pong game today

https://www.dropbox.com/sh/yj029xbw49hrwj2/AABQ7Qc8ISj4ZunN9NTAEVe9a?dl=0

It contains the pong client and its dependencies. It also has the java program as a .jar file, which you can run from the command prompt with the command:

`java -jar AndroidMouse.jar`

If you haven't set up the environment variables to use java from the command line, you can read how to do it here http://stackoverflow.com/questions/1672281/environment-variables-for-java-installation
Although I don't know if this is different for windows 8 or 10.

That dropbox link also has the app apk if anyone wants to install that and try playing pong

**Comment by captjacksparrowz** [comment]
I've got it working
