### ISSUE TITLE
Problems with the code I've uploaded

### ISSUE THREAD

**Issue by Fanchao92** [CourseReps/ECEN489-Spring2016#2]
Sorry, everyone. The 2 versions I uploaded this afternoon are not actually finished yet, and after the debugging and discussion today, I figured there were still some modifications to be made to my part. So I re-wrote some portions of my code, and I've tested it on my simulator(of course, with dummy data of RSSI,GPS and IMU). This time, the files I upload in folder 'Core3' are just .java source files, resources and AndroidManifest. If you copy these files into the project in 'Core2' folder, that should be good, hopefully.

I've highlighted the parts to add code for data collection and data transmission with "TODO" comments in blue. And they are all in the method "onCreateView()" of the MainFragment.java file.

I wrote the code assuming when the user presses the button "refresh", all the data to be displayed will be returned to the main fragment as a list of strings, and the data will be pushed to the database as well, so we don't bother the user to press two buttons, both "refresh" and "push to database". 

By the way, I haven't changed the package name yet, because I guess something would be wrong with the project configuration if I did. Eventually, when we finish all the debugging and integration, we may copy all the stuff into a new project, and rename the package.

Sorry again if you've already added your code to my previous versions.

**Comment by keabro** [comment]
we still need a push to database button in order to send the data to the server. We can't send data to the server without wifi and most of our testing will be outside without wifi.

**Comment by Fanchao92** [comment]
I think I've added a button called "connecting to server". That's supposed
to trigger a data transmission. I'll double-check it.

2016年2月29日星期一，Keaton Brown <notifications@github.com> 写道：
