### ISSUE TITLE
Project 2b

### ISSUE THREAD

**Issue by tbranyon** [CourseReps/ECEN489-Spring2016#8]
Before we divy up tasks, let's make sure we have as many as we know about documented. Comment here if you know of any not listed.

### Missing Features
<li> Data needs to stop recording when orientation is out of tolerance (Main fragment, probably in the run/stop button handler)
<li> Main fragment needs to function based on user-defined preferences in the Settings fragment (server address, baud rate, which variables to log, etc.) (handled throughout the Main Fragment)
<li> OAuth/Maps functionality (John is already on this I believe)

### Known Issues
<li> App runs slow/crashes on startup for some phones (This would be an overall performance/threading task likely)
<li> App crashes when back button is pressed in most or all fragments (onPause() likely culprit)
<li> Issue with MainFragment onDestroy() causes app to crash on exit
<li> App crashes on orientation change (unknown cause)

I'll update this list as people add to it. Try to get this done tonight.

**Comment by tbranyon** [comment]
Unless anyone discovers any more problems (I think we nailed them all down?), I think we can move forward. 

I tried to build a list of tasks on the Project2.md readme page. Go ahead and sign up if you know what you want to do. Assign yourself by tomorrow and have your stuff ready to integrate by Monday. Once you've fixed whichever issue you're working on, commit it to a separate branch of the project and let me know and I'll integrate it into the master branch. Make sure you're pulling the most recent version of the master branch to start with. 

If you have a question about one of the tasks or think any of them should be combined/split/removed, let me know.

@akashatnitr @paulcrouther @keabro @captjacksparrowz @ctg123 @leoyyx2009 @Fanchao92

**Comment by samshore** [comment]
Why are there two checkboxes on the alignment fragment? We only need one to indicate whether or not automatic data collection should check for alignment, right? Right now I don't see anywhere where either is used I think, I might just be missing something though.

**Comment by tbranyon** [comment]
I believe you are correct. Go ahead and pull the extra one out.

**Comment by samshore** [comment]
Ok I just wanted to make sure I wasn't going to break something. I'll change that and make the text more clear.

**Comment by tbranyon** [comment]
By the way, since we never really got into branching with git, if you're unfamiliar with branching:

To create a branch and switch to it, from the 489 repo:
`git checkout -b <your_branch_name>`

You can then commit to and push to this branch like you would the master repository.

To merge, you would run the following:
`git checkout master`  
`git merge <your_branch_name>`  
`git branch -d <your_branch_name> #remove old branch`  

In this case, you don't need to handle the merging, just let me know when your stuff is ready to go and I'll checkout your branch and reconcile it with the main project.

**Comment by keabro** [comment]
Is the LatLong class used anywhere? I see we get Lat Long within the Main fragment, but not with that class.

**Comment by tbranyon** [comment]
Isn't it part of John's mapping stuff?

**Comment by keabro** [comment]
Yes it is thanks.

**Comment by johnlusher** [comment]
Yes it is used to calculate a Lat/Long given a starting geo position, a bearing, and distance.  Used to compute the region bounds for the area to be pulled from the database.

**Comment by samshore** [comment]
My branch should be ready to go @tbranyon. Here are a list of changes:

- The orientation textviews and the graphic color are now updated in the alignment fragment
- The orientation graphic changes from red to green gradually as you move the device
- When the checkbox is marked, the run/stop only auto collects data when the device is oriented properly. When it is not marked, it will auto collect regardless of alignment
- Slight ui changes in the data fragment to make all of the buttons the same size. I also resized the area given to the orientation graphic to remove some white space above the buttons

I think that is everything. Sometimes when the data list is updating the graphic jumps a little bit, but I have absolutely no idea how to fix it. It doesn't really matter, it just bugs me.

**Comment by samshore** [comment]
Also is anyone getting the RSSI? I didn't see that on the readme

**Comment by tbranyon** [comment]
Cool, thanks. I'll check it out when I get a second.

And yeah, whoever wants to do that, go for it. I forgot to list it, my bad.

**Comment by tbranyon** [comment]
We also still need someone to debug the performance issues. So that and internal RSSI are still unassgined.
@akashatnitr @ctg123

**Comment by paulcrouther** [comment]
I only need to add a few lines to the AndroidManifest.xml file to get the rotation to stop crashing the app.

I figure I don't need a whole new branch for that. I've done some scoping for the RSSI wifi problem:

http://stackoverflow.com/questions/13932724/getting-wifi-signal-strength-in-android

How should this be integrated? Another thread?

**Comment by captjacksparrowz** [comment]
I found the partial source of the crash when when back button is pressed. While viewing the MainFragment the serial port.close() line in the onDestroy() method fails. However, this is not the only problem. I seem to get a different error message when I pressed the back button while viewing different screens. This tells me that there is a different error causing the crash for each fragment that is currently being viewed. Hopefully I can have this figured out by tomorrow.

**Comment by Fanchao92** [comment]
Just a question about the checkbox preferences on the settings page. Are they meant to control data collection, or actually all the data are collected but partially displayed according to the checkbox preferences? Besides, there's another multi-choice list with almost the same preferences as all the checkbox preferences on the settings page. Does this list control what to include in the JSON string we push to the server?

**Comment by tbranyon** [comment]
@paulcrouther Yeah, go ahead and commit that to master when you've got that since it's a pretty simple change. I think we want 3G/4G type signal, not WiFi though right?
I was thinking that signal collection would just be another sensor read within "onSensorChanged", but it's probably more complicated than that. If necessary, it can be launched in another thread.

@Fanchao92 I believe the checkbox preferences are just for display and the JSON preferences are for what is pushed. Someone correct me if I'm wrong.
I think I've heard a couple of differing things actually. Unless someone remembers for sure that it's supposed to be one way or another, I think it probably makes sense to display based on those main checkboxes and push to the server (and maybe record?) based on what's in the JSON prefs. Thoughts?

**Comment by leoyyx2009** [comment]
I tried to fix the OnDestroy() problem. Now, I put port.close() to the
OnStop method. The initialization of port operation has been moved to
onStart method. I am not sure whether it is the only problem to lead crash
when exiting, because whenever I click back button, the app will crash.

**Comment by tbranyon** [comment]
@samshore, your branch is merged. Everything works great, thanks. One thing you might add between now and Wednesday is a Toast message to inform the user that recording has stopped. This would show only whenever recording is active and the user passes from alignment to misalignment. Just commit that to master when you get the chance.

For anyone who is branching, make sure when you're done working on a branch that you switch back to master with `git checkout master` when you're done.

@paulcrouther Orientation crash fix looks good, thanks!

**Comment by tbranyon** [comment]
@leoyyx2009 your branch is merged, thanks. 

Branch 'master' is now up to date with fixes for exit crashing, rotation crashing, and alignment-sensitive recording. If you're at the beginning of a change, consider pulling the newest version before diving in further.

**Comment by johnlusher** [comment]
I have noticed that on the database that the timestamp appears to be the same for each entry during the connect to server.   We need to look at this.  It should have samples separated by some amount of time 1-sec intervals, etc...

**Comment by tbranyon** [comment]
I've got that one.

Something that Dr. Huff noted is that we need some kind of compass reading. When we stand with the device aligned vertically, we need to know if we're pointing North, South, East...etc. That was the "mag" part we were talking about before. Anyone want to jump on that? Mag readings need to be included in our data and be displayed, recorded, and transmitted. The readings are currently taken in 'public void onSensorChanged' in MainFragment. These readings are stored to 'DataCollector.magField[]' in three entries (just like orientation). These just need to be included in the recorded data and displayed.

**Comment by johnlusher** [comment]
Also, minor nit, once we are pretty well debugged we need to point the server settings to the application settings and not have the server host address hardcoded as it is now.

**Comment by johnlusher** [comment]
Just ping me whenever you need me to check the server.

**Comment by tbranyon** [comment]
Remaining known issues:
Debug back button crash(es) - Kyle, Paul, Keaton
Performance improvements (fix crashes due to slowness) - ***Still unassigned, unsure if it is still a problem***
Implement dynamic data collection based on user settings - Fanchao
Code organization/cleaning, UI polishing - Keaton
Get internal RSSI - ***Unassigned?***
Include mag field readings in data collection - Chaance
Fix data collection timestamps - Thomas
Read server settings from preferences - ***Unassigned***

Post up if you know of one that needs to be fixed that isn't here.

**Comment by ctg123** [comment]
I am going to look into handling the magnetic field readings to be recorded
and transmitted. Any other classes I need to implement other than the main
fragment?

Also because of my absence I am willing to work wherever there needs
manpower. Just let me know!

**Comment by samshore** [comment]
Oh right now the z field of the orientation is basically a compass reading, with 360/0 being north. I'm not sure how we could make that more obvious though. I guess there could be a N/S/E/W next to the z reading to indicate the direction

**Comment by tbranyon** [comment]
When we rotated the phone around with it vertical, none of the three
orientation readings appeared to change. Is that the case on yours?

**Comment by samshore** [comment]
Are you saying like y=90, x=0, and then when you turn z doesn't change? That doesn't happen for me. I could try to email you a video. That could be easier than trying to explain it.

**Comment by samshore** [comment]
I sent you a link to the video on my drive, I'm pretty sure you should be able to watch it. Now that I look at it though, the closer to vertical the phone gets and the closer to 180 degrees it gets, the more inaccurate it is. It's still relatively accurate, and it improves when you lower the phone so that its closer to parallel with the ground. So there's probably room for improvement if we want to try to do that.

**Comment by tbranyon** [comment]
Ah! You're totally right. Sorry about that. For some reason we were thinking today that the square should have changed during that rotation, but that's absolutely 100% not the case. You want to be able to take data in different compass directions at any given spot. Maybe just replace the "z" label with "degrees" or something. But that completely works, no other work on mag readings is necessary. My bad.

**Comment by johnlusher** [comment]
Let me know if you need me to update or work on anything.  I am currently still working the Fusion Tables OAuth.

**Comment by tbranyon** [comment]
Can someone test the current master branch? On my phone it's almost completely unresponsive right now, but we haven't really changed anything major since Monday, so I want to see if maybe it's just my phone that's causing the issue.

**Comment by samshore** [comment]
It is working fine for me. Do you think uninstalling and reinstalling it might help?

**Comment by captjacksparrowz** [comment]
After class on Monday Akash pointed me in the right direction get this back button fixed, however I think (i might be wrong) the method he showed me requires API 23 which I don't have and I sure most of the phones yall are using don't. I'll try to find a workaround.

**Comment by tbranyon** [comment]
I tried reinstalling. It's still running slow. logcat shows the following output (similar to what we had a week ago): "I/Choreographer: Skipped 61 frames!  The application may be doing too much work on its main thread."
I guess we had a similar issue last week when it ran fine on most phones (including mine) but ran slow on Keaton's... I'm going to look through the MainFragment threading and see what I can find. It seems to be specific to MainFragment. The SettingsFragment doesn't experience the same problem for me.

**Comment by tbranyon** [comment]
So if I comment out the instantiation of AlignmentFragment in MainFragment.onCreate(), the problem goes away... (and for some reason when I do that, the alignment square is still there and updates properly). Am I losing my mind?

**Comment by Fanchao92** [comment]
But isn't the alignment fragment already created in the layout .xml file of
the main fragment? According to the documentations on android's official
website(http://developer.android.com/guide/components/fragments.html):

The android:name attribute in the <fragment> specifies the Fragment
<http://developer.android.com/reference/android/app/Fragment.html> class to
instantiate in the layout.

When the system creates this activity layout, it instantiates each fragment
specified in the layout and calls theonCreateView()
<http://developer.android.com/reference/android/app/Fragment.html#onCreateView(android.view.LayoutInflater,
android.view.ViewGroup, android.os.Bundle)> method for each one, to
retrieve each fragment's layout. The system inserts the View
<http://developer.android.com/reference/android/view/View.html>returned by
the fragment directly in place of the <fragment> element.
So, I guess The alignment fragment should be created if it's already
declared in the layout .xml file of the main fragment?
I don't know if this helps.

**Comment by Fanchao92** [comment]
And I guess we have already declared the alignment fragment in the main
fragment's layout file. At least this is what I've seen:

<fragment
    android:layout_width="175dp"
    android:layout_height="200dp"
    android:name="com.example.fanchaozhou.project1.AlignmentFragment"
    android:id="@+id/align_fragment"
    android:layout_alignParentLeft="true"
    android:layout_alignParentBottom="true"
    android:layout_toLeftOf="@+id/button_clear_all"
    android:layout_toStartOf="@+id/button_clear_all"
    android:layout_alignTop="@+id/button_clear_all" />

So, the alignment should work as expected, since it's already declared
in the main fragment's layout file.

**Comment by tbranyon** [comment]
Ah. Ok. That's interesting. Makes sense then why it is still there even if I comment it out in the java file. Now my question would be, do we need to be creating an instance of AlignmentFragment in MainFragment.java? Is it possible that we're somehow creating 2 AlignmentFragments, one on top of the other? And maybe those are stepping on each other, causing the slow execution?

**Comment by Fanchao92** [comment]
I guess Maybe we are double creating the alignment fragment? Since the
alignment fragment is declared in the layout file, according to the
documentation, the system should invoke its onCreateView method when the
main fragment's layout file is inflated.

2016年3月30日星期三，Thomas Branyon <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> 写道：

**Comment by tbranyon** [comment]
It seems to run fine with the creation stuff commented out in the MainFragment.java file. If no one objects, I'm going to commit that change.

**Comment by tbranyon** [comment]
Fanchao, your branch is merged with the main project. However, I understood the "internal RSSI" to mean we want cell phone signal rather than WiFi. Was that not the case? I thought the normal use case of this app would be walking around outside, where you're probably more concerned with mobile phone signal (3G/4G) rather than WiFi.

**Comment by Fanchao92** [comment]
Ok, I will try to figure out how to get the mobile phone signal.

2016年3月30日星期三，Thomas Branyon <notifications@github.com> 写道：

**Comment by captjacksparrowz** [comment]
new bug: hitting the home button when not displaying the data fragment cause the app to crash when reopened

**Comment by tbranyon** [comment]
That only happens in the AboutUs Fragment for me. Do you get that in
Setting and Maps too?

**Comment by captjacksparrowz** [comment]
Yes
